name: Run Identify Script
on:
  schedule:
    - cron: '20 12 * * *' # Runs at 12:20 PM UTC (6:20 AM CT)
  workflow_dispatch:

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies (if any)
        run: pip install -r requirements.txt

      - name: Run Python script with secrets
        env:
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
          NEWSDATA_API: ${{ secrets.NEWSDATA_API }}
          ALPHA_VANTAGE_API: ${{ secrets.ALPHA_VANTAGE_API }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          LANGSMITH_TRACING: true
          LANGSMITH_ENDPOINT: "https://api.smith.langchain.com"
          LANGSMITH_API_KEY: ${{ secrets.LANGSMITH_API_KEY }}
          LANGSMITH_PROJECT: "wanderer_finance_v2"
        run: python identify.py

      - name: Check for changes
        id: check_changes
        run: echo "::set-output name=changed::$(git status --porcelain | wc -l | tr -d ' ')"

      - name: Commit database changes
        if: steps.check_changes.outputs.changed != '0'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update SQLite database with new Identify"

      - name: Push database changes
        if: steps.check_changes.outputs.changed != '0'
        run: |
          git push origin ${{ github.ref }}